Add reflection hints for io.netty.util.internal.PlatformDependent0 when JDK 21
Netty project has added a reflection specific for JDK 21 with https://github.com/netty/netty/pull/13366
The reflection hints need to be updated to cover also this JDK version.

java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long, long)
        at java.base@21.0.1/java.lang.Class.checkMethod(DynamicHub.java:1065) ~[spring.graalvm:na]
        at java.base@21.0.1/java.lang.Class.getConstructor0(DynamicHub.java:1228) ~[spring.graalvm:na]
        at java.base@21.0.1/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2930) ~[spring.graalvm:na]
        at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:291) ~[na:na]
        at java.base@21.0.1/java.security.AccessController.executePrivileged(AccessController.java:129) ~[na:na]
        at java.base@21.0.1/java.security.AccessController.doPrivileged(AccessController.java:319) ~[na:na]
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:286) ~[na:na]
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:331) ~[na:na]
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:86) ~[na:na]